
--Сreate schema. Use IF NOT EXISTS for reusability.
CREATE SCHEMA IF NOT EXISTS BL_3NF;



--Create SEQUENCE. Use IF NOT EXISTS for reusability.

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_REGIONS START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_COUNTRIES START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_STATES START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_CITIES START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_DISTRICTS START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_ADDRESSES START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_CATEGORIES START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_SUBCATEGORIES START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_COLORS START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_STORAGE_CAPACITIES START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_PRODUCTS START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_SEGMENTS START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_CUSTOMERS START 1; 
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_STORE_TYPES START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_STORE_STATUSES START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_POSITIONS START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_EMPLOYEES START 1; 
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_STORES START 1; 
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_PROMOTION_TYPES START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_PROMOTIONS START 1; 
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_PAYMENT_METHODS START 1; 
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_DATES START 1; 
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_SALES START 1;


--Create Tables.  Use IF NOT EXISTS for reusability. Create parent tables before child tables to avoid foreign key errors.

-- GEOGRAPHY
CREATE TABLE IF NOT EXISTS BL_3NF.CE_REGIONS (
    REGION_ID BIGINT PRIMARY KEY,
    REGION_SRC_ID VARCHAR(100) NOT NULL,
    REGION_NAME VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_COUNTRIES (
    COUNTRY_ID BIGINT PRIMARY KEY,
    COUNTRY_SRC_ID VARCHAR(100) NOT NULL,
    COUNTRY_NAME VARCHAR(100) NOT NULL,
    REGION_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_REGIONS(REGION_ID),
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_STATES (
    STATE_ID BIGINT PRIMARY KEY,
    STATE_SRC_ID VARCHAR(100) NOT NULL,
    STATE_NAME VARCHAR(100) NOT NULL,
    COUNTRY_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_COUNTRIES(COUNTRY_ID),
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_CITIES (
    CITY_ID BIGINT PRIMARY KEY,
    CITY_SRC_ID VARCHAR(100) NOT NULL,
    CITY_NAME VARCHAR(100) NOT NULL,
    REGION_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_STATES(STATE_ID), 
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_DISTRICTS (
    DISTRICT_ID BIGINT PRIMARY KEY,
    DISTRICT_SRC_ID VARCHAR(100) NOT NULL,
    DISTRICT_NAME VARCHAR(100) NOT NULL,
    CITY_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_CITIES(CITY_ID),
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_ADDRESSES (
    ADDRESS_ID BIGINT PRIMARY KEY,
    ADDRESS_SRC_ID VARCHAR(100) NOT NULL,
    DISTRICT_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_DISTRICTS(DISTRICT_ID),
    POSTAL_CODE VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL
);

-- PRODUCTS
CREATE TABLE IF NOT EXISTS BL_3NF.CE_CATEGORIES (
    CATEGORY_ID BIGINT PRIMARY KEY,
    CATEGORY_SRC_ID VARCHAR(100) NOT NULL,
    CATEGORY_NAME VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_SUBCATEGORIES (
    SUBCATEGORY_ID BIGINT PRIMARY KEY,
    SUBCATEGORY_SRC_ID VARCHAR(100) NOT NULL,
    SUBCATEGORY_NAME VARCHAR(100) NOT NULL,
    CATEGORY_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_CATEGORIES(CATEGORY_ID),
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_COLORS (
    COLOR_ID BIGINT PRIMARY KEY,
    COLOR_SRC_ID VARCHAR(100) NOT NULL,
    COLOR_NAME VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_STORAGE_CAPACITIES (
    STORAGE_CAPACITY_ID BIGINT PRIMARY KEY,
    STORAGE_CAPACITY_SRC_ID VARCHAR(100) NOT NULL,
    STORAGE_CAPACITY VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_PRODUCTS_SCD (
    PRODUCT_ID BIGINT NOT NULL,
    PRODUCT_SRC_ID VARCHAR(100) NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    SUBCATEGORY_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_SUBCATEGORIES(SUBCATEGORY_ID),
    MODEL_YEAR INT NOT NULL,
    COLOR_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_COLORS(COLOR_ID),
    STORAGE_CAPACITY_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_STORAGE_CAPACITIES(STORAGE_CAPACITY_ID),
    WARRANTY_PERIOD VARCHAR(100) NOT NULL,
    START_DT DATE NOT NULL,
    END_DT DATE NOT NULL,
    IS_ACTIVE VARCHAR(1) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    PRIMARY KEY (PRODUCT_ID, START_DT)
);

-- CUSTOMERS
CREATE TABLE IF NOT EXISTS BL_3NF.CE_SEGMENTS (
    SEGMENT_ID BIGINT PRIMARY KEY,
    SEGMENT_SRC_ID VARCHAR(100) NOT NULL,
    SEGMENT_NAME VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_CUSTOMERS (
    CUSTOMER_ID BIGINT PRIMARY KEY,
    CUSTOMER_SRC_ID VARCHAR(100) NOT NULL,
    LOYALTY_CARD_NO VARCHAR(100) NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(100) NOT NULL,
    AGE VARCHAR(50) NOT NULL,
    GENDER VARCHAR(50) NOT NULL,
    SEGMENT_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_SEGMENTS(SEGMENT_ID),
    ADDRESS_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_ADDRESSES(ADDRESS_ID),
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL
);

-- EMPLOYEES AND STORES
CREATE TABLE IF NOT EXISTS BL_3NF.CE_POSITIONS (
    POSITION_ID BIGINT PRIMARY KEY,
    POSITION_SRC_ID VARCHAR(100) NOT NULL,
    POSITION_NAME VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_EMPLOYEES (
    EMPLOYEE_ID BIGINT PRIMARY KEY,
    EMPLOYEE_SRC_ID VARCHAR(100) NOT NULL,
    EMPLOYEE_FIRST_NAME VARCHAR(100) NOT NULL,
    EMPLOYEE_LAST_NAME VARCHAR(100) NOT NULL,
    POSITION_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_POSITIONS(POSITION_ID),
    HIRE_DATE DATE NOT NULL,
    EMPLOYEE_EMAIL VARCHAR(100) NOT NULL,
    EMPLOYEE_PHONE VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_STORE_TYPES (
    STORE_TYPE_ID BIGINT PRIMARY KEY,
    STORE_TYPE_SRC_ID VARCHAR(100) NOT NULL,
    STORE_TYPE VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_STORE_STATUSES (
    STORE_STATUS_ID BIGINT PRIMARY KEY,
    STORE_STATUS_SRC_ID VARCHAR(100) NOT NULL,
    STORE_STATUS VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_STORES (
    STORE_ID BIGINT PRIMARY KEY,
    STORE_SRC_ID VARCHAR(100) NOT NULL,
    STORE_NAME VARCHAR(100) NOT NULL,
    STORE_TYPE_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_STORE_TYPES(STORE_TYPE_ID),
    STORE_STATUS_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_STORE_STATUSES(STORE_STATUS_ID),
    STORE_SIZE_SQM INT NOT NULL,
    OPENING_YEAR INT NOT NULL,
    HAS_GENIUS_BAR BOOLEAN NOT NULL,
    MANAGER_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_EMPLOYEES(EMPLOYEE_ID),
    ADDRESS_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_ADDRESSES(ADDRESS_ID),
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL
);

-- PROMOTIONS AND PAYMENT METHODS
CREATE TABLE IF NOT EXISTS BL_3NF.CE_PROMOTION_TYPES (
    PROMOTION_TYPE_ID BIGINT PRIMARY KEY,
    PROMOTION_TYPE_SRC_ID VARCHAR(100) NOT NULL,
    PROMOTION_TYPE VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_PROMOTIONS (
    PROMOTION_ID BIGINT PRIMARY KEY,
    PROMOTION_SRC_ID VARCHAR(100) NOT NULL,
    PROMOTION_NAME VARCHAR(100) NOT NULL,
    PROMOTION_TYPE_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_PROMOTION_TYPES(PROMOTION_TYPE_ID),
    IS_ACTIVE VARCHAR(10) NOT NULL,
    PROMO_START_DATE DATE NOT NULL,
    PROMO_END_DATE DATE NOT NULL,
    DISCOUNT_VALUE DECIMAL(10,2) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_PAYMENT_METHODS (
    PAYMENT_METHOD_ID BIGINT PRIMARY KEY,
    PAYMENT_METHOD_SRC_ID VARCHAR(100) NOT NULL,
    PAYMENT_METHOD_NAME VARCHAR(100) NOT NULL,
    PAYMENT_METHOD_TYPE VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL
);

-- DATES
CREATE TABLE IF NOT EXISTS BL_3NF.CE_DATES (
    DATE_ID BIGINT PRIMARY KEY,
    DATE_SRC_ID VARCHAR(100) NOT NULL,
    FULL_DATE DATE NOT NULL,
    DAY_OF_WEEK VARCHAR(20) NOT NULL,
    DAY_NUMBER INT NOT NULL,
    MONTH_NUMBER INT NOT NULL,
    MONTH_NAME VARCHAR(20) NOT NULL,
    QUARTER INT NOT NULL,
    YEAR INT NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL
);

-- FACTS
CREATE TABLE IF NOT EXISTS BL_3NF.CE_SALES (
    SALE_ID BIGINT PRIMARY KEY,
    SALE_SRC_ID VARCHAR(100) NOT NULL,
    SALE_CHANNEL VARCHAR(50) NOT NULL,
    DATE_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_DATES(DATE_ID),
    PRODUCT_ID BIGINT NOT NULL, -- SCD relationship via ETL logic
    CUSTOMER_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_CUSTOMERS(CUSTOMER_ID),
    STORE_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_STORES(STORE_ID),
    EMPLOYEE_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_EMPLOYEES(EMPLOYEE_ID),
    PROMOTION_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_PROMOTIONS(PROMOTION_ID),
    PAYMENT_METHOD_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_PAYMENT_METHODS(PAYMENT_METHOD_ID),
    ADDRESS_ID BIGINT NOT NULL REFERENCES BL_3NF.CE_ADDRESSES(ADDRESS_ID),
    QUANTITY INT,
    UNIT_PRICE DECIMAL(18,2),
    UNIT_COST DECIMAL(18,2),
    INSERT_DT TIMESTAMP NOT NULL
);






