[pytest]
markers =
    smoke: Smoke tests (DB presence, core UI)
    critical: Critical integrity checks
    unit: Low-level logic tests
    ui: User Interface tests (Selenium)
    integration: Integration tests (API, DB, Cloud)

addopts = --alluredir=allure-results --clean-alluredir
testpaths = Tests
python_files = test_*.py
