
--Сreate schema.
CREATE SCHEMA IF NOT EXISTS BL_DM;

BEGIN; 
--Create SEQUENCE. 
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_PRODUCTS_SCD START 1;
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_CUSTOMERS START 1;
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_STORES START 1;
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_EMPLOYEES START 1;
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_PROMOTIONS START 1;
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_PAYMENT_METHODS START 1;
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_FCT_SALES_DD START 1;


--Create Tables.  
CREATE TABLE IF NOT EXISTS BL_DM.DIM_PRODUCTS_SCD (
    PRODUCT_SURR_ID BIGINT NOT NULL,
    PRODUCT_SRC_ID BIGINT NOT NULL,
    PRODUCT_NAME VARCHAR(250) NOT NULL,
    CATEGORY_ID BIGINT NOT NULL,
    CATEGORY_NAME VARCHAR(250) NOT NULL,
    SUBCATEGORY_ID BIGINT NOT NULL,
    SUBCATEGORY_NAME VARCHAR(250) NOT NULL,
    MODEL_YEAR INT NOT NULL,
    COLOR_ID BIGINT NOT NULL,
    COLOR_NAME VARCHAR(250) NOT NULL,
    STORAGE_CAPACITY_ID  BIGINT NOT NULL,
    STORAGE_CAPACITY VARCHAR(250) NOT NULL,
    WARRANTY_PERIOD VARCHAR(250) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    START_DT DATE NOT NULL,
    END_DT DATE NOT NULL,
    IS_ACTIVE VARCHAR(1) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    CONSTRAINT PK_DIM_PRODUCTS_SCD PRIMARY KEY (PRODUCT_SURR_ID)
);

CREATE TABLE IF NOT EXISTS BL_DM.DIM_CUSTOMERS (
    CUSTOMER_SURR_ID BIGINT NOT NULL,
    CUSTOMER_SRC_ID BIGINT NOT NULL,
    LOYALITY_CARD_NO VARCHAR(250) NOT NULL,
    FIRST_NAME VARCHAR(250) NOT NULL,
    LAST_NAME VARCHAR(250) NOT NULL,
    EMAIL VARCHAR(250) NOT NULL,
    PHONE VARCHAR(250) NOT NULL,
    AGE VARCHAR(250) NOT NULL,
    GENDER VARCHAR(250) NOT NULL,
    SEGMENT_ID BIGINT NOT NULL,
    SEGMET_NAME VARCHAR(250) NOT NULL,
    ADDRESS_ID BIGINT NOT NULL,
    ADDRESS VARCHAR(350) NOT NULL,
    POSTAL_CODE VARCHAR(250) NOT NULL,
    DISTRICT_ID BIGINT NOT NULL,
    DISTRICT_NAME VARCHAR(250) NOT NULL,
    CITY_ID BIGINT NOT NULL,
    CITY_NAME VARCHAR(250) NOT NULL,
    STATE_ID BIGINT NOT NULL,
    STATE_NAME VARCHAR(250) NOT NULL,
    COUNTRY_ID BIGINT NOT NULL,
    COUNTRY_NAME VARCHAR(250) NOT NULL,
    REGION_ID BIGINT NOT NULL,
    REGION_NAME VARCHAR(250) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL,
    CONSTRAINT PK_DIM_CUSTOMERS PRIMARY KEY (CUSTOMER_SURR_ID)
);

CREATE TABLE IF NOT EXISTS BL_DM.DIM_STORES (
    STORE_SURR_ID BIGINT NOT NULL,
    STORE_SRC_ID BIGINT NOT NULL,
    STORE_NAME VARCHAR(250) NOT NULL,
    STORE_TYPE_ID BIGINT NOT NULL,
    STORE_TYPE VARCHAR(250) NOT NULL,
    STORE_STATUS_ID BIGINT NOT NULL,
    STORE_STATUS VARCHAR(250) NOT NULL,
    STORE_SIZE_SQM INT NOT NULL,
    OPENING_YEAR INT NOT NULL,
    HAS_GENIUS_BAR BOOLEAN NOT NULL,
    MANAGER_ID BIGINT NOT NULL,
    MANAGER_FIRST_NAME VARCHAR(250) NOT NULL,
    MANAGER_LAST_NAME VARCHAR(250) NOT NULL,
    ADDRESS_ID BIGINT NOT NULL,
    ADDRESS VARCHAR(350) NOT NULL,
    POSTAL_CODE VARCHAR(250) NOT NULL,
    DISTRICT_ID BIGINT NOT NULL,
    DISTRICT_NAME VARCHAR(250) NOT NULL,
    CITY_ID BIGINT NOT NULL,
    CITY_NAME VARCHAR(250) NOT NULL,
    STATE_ID BIGINT NOT NULL,
    STATE_NAME VARCHAR(250) NOT NULL,
    COUNTRY_ID BIGINT NOT NULL,
    COUNTRY_NAME VARCHAR(100) NOT NULL,
    REGION_ID BIGINT NOT NULL,
    REGION_NAME VARCHAR(250) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL,
    CONSTRAINT PK_DIM_STORES PRIMARY KEY (STORE_SURR_ID)
);

CREATE TABLE IF NOT EXISTS BL_DM.DIM_EMPLOYEES (
    EMPLOYEE_SURR_ID BIGINT NOT NULL,
    EMPLOYEE_SRC_ID BIGINT NOT NULL,
    LOYALTY_CARD_NO VARCHAR(250) NOT NULL,
    FIRST_NAME VARCHAR(250) NOT NULL,
    LAST_NAME VARCHAR(250) NOT NULL,
    POSITION_ID BIGINT NOT NULL,
    POSITION_NAME VARCHAR(250) NOT NULL,
    HIRE_DATE DATE NOT NULL,
    EMAIL VARCHAR(250) NOT NULL,
    PHONE VARCHAR(250) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL,
    CONSTRAINT PK_DIM_EMPLOYEES PRIMARY KEY (EMPLOYEE_SURR_ID)
);

CREATE TABLE IF NOT EXISTS BL_DM.DIM_PROMOTIONS (
    PROMOTION_SURR_ID BIGINT NOT NULL,
    PROMOTION_SRC_ID BIGINT NOT NULL,
    PROMOTION_NAME VARCHAR(250) NOT NULL,
    PROMOTION_TYPE_ID BIGINT NOT NULL,
    PROMOTION_TYPE VARCHAR(250) NOT NULL,
    IS_ACTIVE VARCHAR(10) NOT NULL,
    PROMO_START DATE NOT NULL,
    PROMO_END DATE NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL,
    CONSTRAINT PK_DIM_PROMOTIONS PRIMARY KEY (PROMOTION_SURR_ID)
);

CREATE TABLE IF NOT EXISTS BL_DM.DIM_PAYMENT_METHODS (
    PAYMENT_METHOD_SURR_ID BIGINT NOT NULL,
    PAYMENT_METHOD_SRC_ID BIGINT NOT NULL,
    PAYMENT_METHOD_NAME VARCHAR(250) NOT NULL,
    PAYMENT_METHOD_TYPE VARCHAR(250) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL,
    CONSTRAINT PK_DIM_PAYMENT_METHODS PRIMARY KEY (PAYMENT_METHOD_SURR_ID)
);

CREATE TABLE IF NOT EXISTS BL_DM.DIM_DATES (
    DATE_SURR_ID BIGINT NOT NULL,           
    FULL_DATE DATE NOT NULL,          
    DAY_OF_WEEK VARCHAR(15) NOT NULL,   
    DAY_NUMBER INT NOT NULL,           
    MONTH_NUMBER INT NOT NULL,           
    MONTH_NAME VARCHAR(15) NOT NULL,   
    QUARTER INT NOT NULL,           
    YEAR INT NOT NULL,           
    INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    CONSTRAINT PK_DIM_DATES PRIMARY KEY (DATE_SURR_ID)
);

CREATE TABLE IF NOT EXISTS BL_DM.FCT_SALES_DD (
    SALE_SURR_ID BIGINT NOT NULL,
    SALE_SRC_ID BIGINT NOT NULL,
    SALE_CHANNEL VARCHAR(250) NOT NULL,
    DATE_SURR_ID BIGINT NOT NULL REFERENCES BL_DM.DIM_DATES(DATE_SURR_ID), 
    PRODUCT_SURR_ID BIGINT NOT NULL REFERENCES BL_DM.DIM_PRODUCTS_SCD(PRODUCT_SURR_ID),
    CUSTOMER_SURR_ID BIGINT NOT NULL REFERENCES BL_DM.DIM_CUSTOMERS(CUSTOMER_SURR_ID),
    STORE_SURR_ID BIGINT NOT NULL REFERENCES BL_DM.DIM_STORES(STORE_SURR_ID),
    EMPLOYEE_SURR_ID BIGINT NOT NULL REFERENCES BL_DM.DIM_EMPLOYEES(EMPLOYEE_SURR_ID),
    PAYMENT_METHOD_SURR_ID BIGINT NOT NULL REFERENCES BL_DM.DIM_PAYMENT_METHODS(PAYMENT_METHOD_SURR_ID),
    PROMOTION_SURR_ID BIGINT NOT NULL REFERENCES BL_DM.DIM_PROMOTIONS(PROMOTION_SURR_ID),
    DISCOUNT_VALUE DECIMAL(10,2) NOT NULL,
    QUANTITY INT,
    UNIT_PRICE DECIMAL(18,2),
    UNIT_COST DECIMAL(18,2),
    TOTAL_REVENUE DECIMAL(18,2),
    GROSS_PROFIT DECIMAL(18,2),
    INSERT_DT TIMESTAMP NOT NULL,
    CONSTRAINT PK_FCT_SALES_DD PRIMARY KEY (SALE_SURR_ID)
);
COMMIT;

-- Add default row.
BEGIN;
INSERT INTO BL_DM.DIM_PRODUCTS_SCD (PRODUCT_SURR_ID, PRODUCT_SRC_ID, PRODUCT_NAME, CATEGORY_ID, CATEGORY_NAME,
    SUBCATEGORY_ID, SUBCATEGORY_NAME, MODEL_YEAR, COLOR_ID, COLOR_NAME, 
    STORAGE_CAPACITY_ID, STORAGE_CAPACITY, WARRANTY_PERIOD, SOURCE_SYSTEM, 
    SOURCE_ENTITY, START_DT, END_DT, IS_ACTIVE, INSERT_DT)
SELECT -1, -1, 'n. a.', -1, 'n. a.', -1, 'n. a.', 0, -1, 'n. a.', -1, 'n. a.', 'n. a.', 'MANUAL', 'MANUAL', '1900-01-01', '9999-12-31', 'N', NOW()
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_PRODUCTS_SCD WHERE PRODUCT_SURR_ID = -1);


INSERT INTO BL_DM.DIM_CUSTOMERS (CUSTOMER_SURR_ID, CUSTOMER_SRC_ID, LOYALITY_CARD_NO, FIRST_NAME, LAST_NAME, 
    EMAIL, PHONE, AGE, GENDER, SEGMENT_ID, SEGMET_NAME, ADDRESS_ID, ADDRESS, 
    POSTAL_CODE, DISTRICT_ID, DISTRICT_NAME, CITY_ID, CITY_NAME, STATE_ID, 
    STATE_NAME, COUNTRY_ID, COUNTRY_NAME, REGION_ID, REGION_NAME, 
    SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
SELECT -1, -1, 'n. a.', 'n. a.', 'n. a.', 'n. a.', 'n. a.', 'n. a.', 'n. a.', -1, 'n. a.', -1, 'n. a.', 'n. a.', -1, 'n. a.', -1, 'n. a.', -1, 'n. a.', 
       -1, 'n. a.', -1, 'n. a.', 'MANUAL', 'MANUAL', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_CUSTOMERS WHERE CUSTOMER_SURR_ID = -1);


INSERT INTO BL_DM.DIM_STORES (STORE_SURR_ID, STORE_SRC_ID, STORE_NAME, STORE_TYPE_ID, STORE_TYPE, 
    STORE_STATUS_ID, STORE_STATUS, STORE_SIZE_SQM, OPENING_YEAR, HAS_GENIUS_BAR, 
    MANAGER_ID, MANAGER_FIRST_NAME, MANAGER_LAST_NAME, ADDRESS_ID, ADDRESS, 
    POSTAL_CODE, DISTRICT_ID, DISTRICT_NAME, CITY_ID, CITY_NAME, STATE_ID, 
    STATE_NAME, COUNTRY_ID, COUNTRY_NAME, REGION_ID, REGION_NAME, 
    SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
SELECT -1, -1, 'n. a.', -1, 'n. a.', -1, 'n. a.', 0, 0, FALSE, -1, 'n. a.', 'n. a.', -1, 'n. a.', 'n. a.', -1, 'n. a.', -1, 'n. a.', 
       -1, 'n. a.', -1, 'n. a.', -1, 'n. a.', 'MANUAL', 'MANUAL', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_STORES WHERE STORE_SURR_ID = -1);


INSERT INTO BL_DM.DIM_EMPLOYEES (EMPLOYEE_SURR_ID, EMPLOYEE_SRC_ID, LOYALTY_CARD_NO, FIRST_NAME, LAST_NAME, 
    POSITION_ID, POSITION_NAME, HIRE_DATE, EMAIL, PHONE, 
    SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
SELECT -1, -1, 'n. a.', 'n. a.', 'n. a.', -1, 'n. a.', '1900-01-01', 'n. a.', 'n. a.', 'MANUAL', 'MANUAL', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_EMPLOYEES WHERE EMPLOYEE_SURR_ID = -1);


INSERT INTO BL_DM.DIM_PROMOTIONS (PROMOTION_SURR_ID, PROMOTION_SRC_ID, PROMOTION_NAME, PROMOTION_TYPE_ID, 
    PROMOTION_TYPE, IS_ACTIVE, PROMO_START, PROMO_END, 
    SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
SELECT -1, -1, 'n. a.', -1, 'n. a.', 'n. a.', '1900-01-01', '9999-12-31', 'MANUAL', 'MANUAL', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_PROMOTIONS WHERE PROMOTION_SURR_ID = -1);


INSERT INTO BL_DM.DIM_PAYMENT_METHODS (PAYMENT_METHOD_SURR_ID, PAYMENT_METHOD_SRC_ID, PAYMENT_METHOD_NAME, 
    PAYMENT_METHOD_TYPE, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
SELECT -1, -1, 'n. a.', 'n. a.', 'MANUAL', 'MANUAL', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_PAYMENT_METHODS WHERE PAYMENT_METHOD_SURR_ID = -1);
COMMIT;








