
--Create a procedure to insert Default Rows into BL_3NF tables
CREATE OR REPLACE PROCEDURE BL_CL.PRC_INSERT_DEFAULT_ROWS_3NF()
LANGUAGE plpgsql AS $$
DECLARE
    v_proc_name CONSTANT TEXT := 'PRC_INSERT_DEFAULT_ROWS_3NF';
    v_rows_inserted INT := 0;
    v_cnt INT;
BEGIN
    INSERT INTO BL_3NF.CE_REGIONS (REGION_ID, REGION_SRC_ID, REGION_NAME, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT) 
    SELECT -1, 'n. a.', 'n. a.', 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_REGIONS WHERE REGION_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    INSERT INTO BL_3NF.CE_COUNTRIES (COUNTRY_ID, COUNTRY_SRC_ID, COUNTRY_NAME, REGION_ID, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, 'n. a.', 'n. a.', -1, 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_COUNTRIES WHERE COUNTRY_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    INSERT INTO BL_3NF.CE_STATES (STATE_ID, STATE_SRC_ID, STATE_NAME, COUNTRY_ID, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, 'n. a.', 'n. a.', -1, 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_STATES WHERE STATE_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    INSERT INTO BL_3NF.CE_CITIES (CITY_ID, CITY_SRC_ID, CITY_NAME, REGION_ID, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, 'n. a.', 'n. a.', -1, 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_CITIES WHERE CITY_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    INSERT INTO BL_3NF.CE_DISTRICTS (DISTRICT_ID, DISTRICT_SRC_ID, DISTRICT_NAME, CITY_ID, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, 'n. a.', 'n. a.', -1, 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_DISTRICTS WHERE DISTRICT_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    INSERT INTO BL_3NF.CE_ADDRESSES (ADDRESS_ID, ADDRESS_SRC_ID, DISTRICT_ID, POSTAL_CODE, ADDRESS, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, 'n. a.', -1, 'n. a.', 'n. a.', 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_ADDRESSES WHERE ADDRESS_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    INSERT INTO BL_3NF.CE_CATEGORIES (CATEGORY_ID, CATEGORY_SRC_ID, CATEGORY_NAME, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, 'n. a.', 'n. a.', 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_CATEGORIES WHERE CATEGORY_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    INSERT INTO BL_3NF.CE_SUBCATEGORIES (SUBCATEGORY_ID, SUBCATEGORY_SRC_ID, SUBCATEGORY_NAME, CATEGORY_ID, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, 'n. a.', 'n. a.', -1, 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_SUBCATEGORIES WHERE SUBCATEGORY_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    INSERT INTO BL_3NF.CE_COLORS (COLOR_ID, COLOR_SRC_ID, COLOR_NAME, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, 'n. a.', 'n. a.', 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_COLORS WHERE COLOR_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    INSERT INTO BL_3NF.CE_STORAGE_CAPACITIES (STORAGE_CAPACITY_ID, STORAGE_CAPACITY_SRC_ID, STORAGE_CAPACITY, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, 'n. a.', 'n. a.', 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_STORAGE_CAPACITIES WHERE STORAGE_CAPACITY_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    INSERT INTO BL_3NF.CE_PRODUCTS_SCD (PRODUCT_ID, PRODUCT_SRC_ID, PRODUCT_NAME, SUBCATEGORY_ID, MODEL_YEAR, COLOR_ID, STORAGE_CAPACITY_ID, WARRANTY_PERIOD, START_DT, END_DT, IS_ACTIVE, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT)
    SELECT -1, 'n. a.', 'n. a.', -1, 0, -1, -1, 'n. a.', '1900-01-01', '9999-12-31', 'Y', 'MANUAL', 'MANUAL', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_PRODUCTS_SCD WHERE PRODUCT_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    INSERT INTO BL_3NF.CE_SEGMENTS (SEGMENT_ID, SEGMENT_SRC_ID, SEGMENT_NAME, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, 'n. a.', 'n. a.', 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_SEGMENTS WHERE SEGMENT_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    INSERT INTO BL_3NF.CE_CUSTOMERS (CUSTOMER_ID, CUSTOMER_SRC_ID, LOYALTY_CARD_NO, FIRST_NAME, LAST_NAME, EMAIL, PHONE, AGE, GENDER, SEGMENT_ID, ADDRESS_ID, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, 'n. a.', 'n. a.', 'n. a.', 'n. a.', 'n. a.', 'n. a.', 'n. a.', 'n. a.', -1, -1, 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_CUSTOMERS WHERE CUSTOMER_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    INSERT INTO BL_3NF.CE_POSITIONS (POSITION_ID, POSITION_SRC_ID, POSITION_NAME, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, 'n. a.', 'n. a.', 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_POSITIONS WHERE POSITION_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    INSERT INTO BL_3NF.CE_EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_SRC_ID, EMPLOYEE_FIRST_NAME, EMPLOYEE_LAST_NAME, POSITION_ID, HIRE_DATE, EMPLOYEE_EMAIL, EMPLOYEE_PHONE, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, 'n. a.', 'n. a.', 'n. a.', -1, '1900-01-01', 'n. a.', 'n. a.', 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_EMPLOYEES WHERE EMPLOYEE_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    INSERT INTO BL_3NF.CE_STORE_TYPES (STORE_TYPE_ID, STORE_TYPE_SRC_ID, STORE_TYPE, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, 'n. a.', 'n. a.', 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_STORE_TYPES WHERE STORE_TYPE_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    INSERT INTO BL_3NF.CE_STORE_STATUSES (STORE_STATUS_ID, STORE_STATUS_SRC_ID, STORE_STATUS, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, 'n. a.', 'n. a.', 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_STORE_STATUSES WHERE STORE_STATUS_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    INSERT INTO BL_3NF.CE_STORES (STORE_ID, STORE_SRC_ID, STORE_NAME, STORE_TYPE_ID, STORE_STATUS_ID, STORE_SIZE_SQM, OPENING_YEAR, HAS_GENIUS_BAR, MANAGER_ID, ADDRESS_ID, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, 'n. a.', 'n. a.', -1, -1, 0, 0, 'Y', -1, -1, 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_STORES WHERE STORE_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    INSERT INTO BL_3NF.CE_PROMOTION_TYPES (PROMOTION_TYPE_ID, PROMOTION_TYPE_SRC_ID, PROMOTION_TYPE, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, 'n. a.', 'n. a.', 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_PROMOTION_TYPES WHERE PROMOTION_TYPE_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    INSERT INTO BL_3NF.CE_PROMOTIONS (PROMOTION_ID, PROMOTION_SRC_ID, PROMOTION_NAME, PROMOTION_TYPE_ID, IS_ACTIVE, PROMO_START_DATE, PROMO_END_DATE, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, 'n. a.', 'n. a.', -1, 'n. a.', '1900-01-01', '1900-01-01', 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_PROMOTIONS WHERE PROMOTION_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    INSERT INTO BL_3NF.CE_PAYMENT_METHODS (PAYMENT_METHOD_ID, PAYMENT_METHOD_SRC_ID, PAYMENT_METHOD_NAME, PAYMENT_METHOD_TYPE, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, 'n. a.', 'n. a.', 'n. a.', 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_PAYMENT_METHODS WHERE PAYMENT_METHOD_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;
    CALL BL_CL.PRC_WRITE_LOG(v_proc_name, v_rows_inserted, 'SUCCESS', 'Default Rows inserted 3NF');
EXCEPTION WHEN OTHERS THEN
    CALL BL_CL.PRC_WRITE_LOG(v_proc_name, 0, 'ERROR', SQLERRM);
    RAISE;
END; $$;


