
--Create a procedure to insert Default Rows into BL_DM tables

CREATE OR REPLACE PROCEDURE BL_CL.PRC_INIT_DM_DEFAULT_ROWS()
LANGUAGE plpgsql AS $$
DECLARE
    v_proc_name CONSTANT TEXT := 'PRC_INIT_DM_DEFAULT_ROWS';
    v_rows_inserted INT := 0;
    v_cnt INT;
BEGIN
    -- DIM_PRODUCTS_SCD
    INSERT INTO BL_DM.DIM_PRODUCTS_SCD (PRODUCT_SURR_ID, PRODUCT_SRC_ID, PRODUCT_NAME, CATEGORY_ID, CATEGORY_NAME, SUBCATEGORY_ID, SUBCATEGORY_NAME, MODEL_YEAR, COLOR_ID, COLOR_NAME, STORAGE_CAPACITY_ID, STORAGE_CAPACITY, WARRANTY_PERIOD, SOURCE_SYSTEM, SOURCE_ENTITY, START_DT, END_DT, IS_ACTIVE, INSERT_DT)
    SELECT -1, -1, 'n. a.', -1, 'n. a.', -1, 'n. a.', 0, -1, 'n. a.', -1, 'n. a.', 'n. a.', 'MANUAL', 'MANUAL', '1900-01-01', '9999-12-31', 'N', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_PRODUCTS_SCD WHERE PRODUCT_SURR_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    -- DIM_CUSTOMERS
    INSERT INTO BL_DM.DIM_CUSTOMERS (CUSTOMER_SURR_ID, CUSTOMER_SRC_ID, LOYALITY_CARD_NO, FIRST_NAME, LAST_NAME, EMAIL, PHONE, AGE, GENDER, SEGMENT_ID, SEGMENT_NAME, ADDRESS_ID, ADDRESS, POSTAL_CODE, DISTRICT_ID, DISTRICT_NAME, CITY_ID, CITY_NAME, STATE_ID, STATE_NAME, COUNTRY_ID, COUNTRY_NAME, REGION_ID, REGION_NAME, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, -1, 'n. a.', 'n. a.', 'n. a.', 'n. a.', 'n. a.', 'n. a.', 'n. a.', -1, 'n. a.', -1, 'n. a.', 'n. a.', -1, 'n. a.', -1, 'n. a.', -1, 'n. a.', -1, 'n. a.', -1, 'n. a.', 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_CUSTOMERS WHERE CUSTOMER_SURR_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    -- DIM_STORES
    INSERT INTO BL_DM.DIM_STORES (STORE_SURR_ID, STORE_SRC_ID, STORE_NAME, STORE_TYPE_ID, STORE_TYPE, STORE_STATUS_ID, STORE_STATUS, STORE_SIZE_SQM, OPENING_YEAR, HAS_GENIUS_BAR, MANAGER_ID, MANAGER_FIRST_NAME, MANAGER_LAST_NAME, ADDRESS_ID, ADDRESS, POSTAL_CODE, DISTRICT_ID, DISTRICT_NAME, CITY_ID, CITY_NAME, STATE_ID, STATE_NAME, COUNTRY_ID, COUNTRY_NAME, REGION_ID, REGION_NAME, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, -1, 'n. a.', -1, 'n. a.', -1, 'n. a.', 0, 0, FALSE, -1, 'n. a.', 'n. a.', -1, 'n. a.', 'n. a.', -1, 'n. a.', -1, 'n. a.', -1, 'n. a.', -1, 'n. a.', -1, 'n. a.', 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_STORES WHERE STORE_SURR_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    -- DIM_EMPLOYEES
    INSERT INTO BL_DM.DIM_EMPLOYEES (EMPLOYEE_SURR_ID, EMPLOYEE_SRC_ID, FIRST_NAME, LAST_NAME, POSITION_ID, POSITION_NAME, HIRE_DATE, EMAIL, PHONE, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, -1, 'n. a.', 'n. a.', -1, 'n. a.', '1900-01-01', 'n. a.', 'n. a.', 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_EMPLOYEES WHERE EMPLOYEE_SURR_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    -- DIM_PROMOTIONS
    INSERT INTO BL_DM.DIM_PROMOTIONS (PROMOTION_SURR_ID, PROMOTION_SRC_ID, PROMOTION_NAME, PROMOTION_TYPE_ID, PROMOTION_TYPE, IS_ACTIVE, PROMO_START, PROMO_END, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, -1, 'n. a.', -1, 'n. a.', 'n. a.', '1900-01-01', '1900-01-01', 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_PROMOTIONS WHERE PROMOTION_SURR_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;

    -- DIM_PAYMENT_METHODS
    INSERT INTO BL_DM.DIM_PAYMENT_METHODS (PAYMENT_METHOD_SURR_ID, PAYMENT_METHOD_SRC_ID, PAYMENT_METHOD_NAME, PAYMENT_METHOD_TYPE, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    SELECT -1, -1, 'n. a.', 'n. a.', 'MANUAL', 'MANUAL', '1900-01-01', '1900-01-01'
    WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_PAYMENT_METHODS WHERE PAYMENT_METHOD_SURR_ID = -1);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rows_inserted := v_rows_inserted + v_cnt;
    CALL BL_CL.PRC_WRITE_LOG(v_proc_name, v_rows_inserted, 'SUCCESS', 'Default Rows inserted DM');
EXCEPTION WHEN OTHERS THEN
    CALL BL_CL.PRC_WRITE_LOG(v_proc_name, 0, 'ERROR', SQLERRM);
    RAISE;
END; $$;


