
--Create a Master procedure to load BL_3NF
CREATE OR REPLACE PROCEDURE BL_CL.PRC_LOAD_3NF_DATA_ALL()
LANGUAGE plpgsql AS $$
DECLARE
    v_proc_name CONSTANT TEXT := 'PRC_LOAD_3NF_DATA_ALL';
BEGIN
    CALL BL_CL.PRC_LOAD_SRC_APPLE_ONLINE();
    CALL BL_CL.PRC_LOAD_SRC_APPLE_POS();
    CALL BL_CL.PRC_INSERT_DEFAULT_ROWS_3NF();
    CALL BL_CL.PRC_LOAD_CE_REGIONS();
    CALL BL_CL.PRC_LOAD_CE_COUNTRIES();
    CALL BL_CL.PRC_LOAD_CE_STATES();
    CALL BL_CL.PRC_LOAD_CE_CITIES();
    CALL BL_CL.PRC_LOAD_CE_DISTRICTS();
    CALL BL_CL.PRC_LOAD_CE_ADDRESSES();
    CALL BL_CL.PRC_LOAD_CE_CATEGORIES();
    CALL BL_CL.PRC_LOAD_CE_SUBCATEGORIES();
    CALL BL_CL.PRC_LOAD_CE_COLORS();
    CALL BL_CL.PRC_LOAD_CE_STORAGE_CAPACITIES();
    CALL BL_CL.PRC_LOAD_CE_PRODUCTS_SCD();
    CALL BL_CL.PRC_LOAD_CE_POSITIONS();
    CALL BL_CL.PRC_LOAD_CE_EMPLOYEES();
    CALL BL_CL.PRC_LOAD_CE_STORE_TYPES();
    CALL BL_CL.PRC_LOAD_CE_STORE_STATUSES();
    CALL BL_CL.PRC_LOAD_CE_STORES();
    CALL BL_CL.PRC_LOAD_CE_SEGMENTS();
    CALL BL_CL.PRC_LOAD_CE_CUSTOMERS();
    CALL BL_CL.PRC_LOAD_CE_PROMOTION_TYPES();
    CALL BL_CL.PRC_LOAD_CE_PROMOTIONS();
    CALL BL_CL.PRC_LOAD_CE_PAYMENT_METHODS();
    CALL BL_CL.PRC_LOAD_CE_SALES_INCREMENTAL();
    CALL BL_CL.PRC_WRITE_LOG(v_proc_name, 1, 'SUCCESS', 'Full 3NF load layer finished');
EXCEPTION WHEN OTHERS THEN
    CALL BL_CL.PRC_WRITE_LOG(v_proc_name, 0, 'ERROR', 'Master failed at: ' || SQLERRM);
    RAISE;
END; $$;





