

--Fill the table with data. I chose the range from 2022 to 2026.
BEGIN;
INSERT INTO BL_DM.DIM_DATES (DATE_SURR_ID, FULL_DATE, DAY_OF_WEEK, DAY_NUMBER, MONTH_NUMBER, MONTH_NAME, QUARTER, YEAR)
SELECT 
    TO_CHAR(datum, 'YYYYMMDD')::BIGINT AS DATE_SURR_ID,
    datum AS FULL_DATE,
    TO_CHAR(datum, 'TMDay') AS DAY_OF_WEEK, 
    EXTRACT(DAY FROM datum) AS DAY_NUMBER,
    EXTRACT(MONTH FROM datum) AS MONTH_NUMBER,
    TO_CHAR(datum, 'TMMonth') AS MONTH_NAME,
    EXTRACT(QUARTER FROM datum) AS QUARTER,
    EXTRACT(YEAR FROM datum) AS YEAR
FROM (
    SELECT '2022-01-01'::DATE + sequence.day AS datum
    FROM generate_series(0, (DATE '2026-12-31' - DATE '2022-01-01')) AS sequence(day)
) AS d
ON CONFLICT (DATE_SURR_ID) DO NOTHING;
COMMIT;
