
--Сreate schema for Business Layer Dimensional Model. Use IF NOT EXISTS for reusability.
CREATE SCHEMA IF NOT EXISTS BL_DM;

BEGIN; 
--Create SEQUENCE. Use IF NOT EXISTS for reusability.
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_PRODUCTS_SCD START 1;
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_CUSTOMERS START 1;
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_STORES START 1;
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_EMPLOYEES START 1;
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_PROMOTIONS START 1;
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_PAYMENT_METHODS START 1;
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_FCT_SALES_DD START 1;

--Create Tables. Use IF NOT EXISTS for reusability. 
--DIM_PRODUCTS_SCD TYPE 2
CREATE TABLE IF NOT EXISTS BL_DM.DIM_PRODUCTS_SCD (
    PRODUCT_SURR_ID BIGINT NOT NULL,
    PRODUCT_SRC_ID BIGINT NOT NULL,
    PRODUCT_NAME VARCHAR(250) NOT NULL,
    CATEGORY_ID BIGINT NOT NULL,
    CATEGORY_NAME VARCHAR(250) NOT NULL,
    SUBCATEGORY_ID BIGINT NOT NULL,
    SUBCATEGORY_NAME VARCHAR(250) NOT NULL,
    MODEL_YEAR INT NOT NULL,
    COLOR_ID BIGINT NOT NULL,
    COLOR_NAME VARCHAR(250) NOT NULL,
    STORAGE_CAPACITY_ID  BIGINT NOT NULL,
    STORAGE_CAPACITY VARCHAR(250) NOT NULL,
    WARRANTY_PERIOD VARCHAR(250) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    START_DT TIMESTAMP NOT NULL,
    END_DT TIMESTAMP NOT NULL,
    IS_ACTIVE VARCHAR(1) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    CONSTRAINT PK_DIM_PRODUCTS_SCD PRIMARY KEY (PRODUCT_SURR_ID)
);
--DIM_CUSTOMERS
CREATE TABLE IF NOT EXISTS BL_DM.DIM_CUSTOMERS (
    CUSTOMER_SURR_ID BIGINT NOT NULL,
    CUSTOMER_SRC_ID BIGINT NOT NULL,
    LOYALITY_CARD_NO VARCHAR(250) NOT NULL,
    FIRST_NAME VARCHAR(250) NOT NULL,
    LAST_NAME VARCHAR(250) NOT NULL,
    EMAIL VARCHAR(250) NOT NULL,
    PHONE VARCHAR(250) NOT NULL,
    AGE VARCHAR(250) NOT NULL,
    GENDER VARCHAR(250) NOT NULL,
    SEGMENT_ID BIGINT NOT NULL,
    SEGMENT_NAME VARCHAR(250) NOT NULL,
    ADDRESS_ID BIGINT NOT NULL,
    ADDRESS VARCHAR(350) NOT NULL,
    POSTAL_CODE VARCHAR(250) NOT NULL,
    DISTRICT_ID BIGINT NOT NULL,
    DISTRICT_NAME VARCHAR(250) NOT NULL,
    CITY_ID BIGINT NOT NULL,
    CITY_NAME VARCHAR(250) NOT NULL,
    STATE_ID BIGINT NOT NULL,
    STATE_NAME VARCHAR(250) NOT NULL,
    COUNTRY_ID BIGINT NOT NULL,
    COUNTRY_NAME VARCHAR(250) NOT NULL,
    REGION_ID BIGINT NOT NULL,
    REGION_NAME VARCHAR(250) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL,
    CONSTRAINT PK_DIM_CUSTOMERS PRIMARY KEY (CUSTOMER_SURR_ID),
    CONSTRAINT UNQ_DIM_CUST_SRC UNIQUE (CUSTOMER_SRC_ID, SOURCE_SYSTEM)
);
--DIM_STORES
CREATE TABLE IF NOT EXISTS BL_DM.DIM_STORES (
    STORE_SURR_ID BIGINT NOT NULL,
    STORE_SRC_ID BIGINT NOT NULL,
    STORE_NAME VARCHAR(250) NOT NULL,
    STORE_TYPE_ID BIGINT NOT NULL,
    STORE_TYPE VARCHAR(250) NOT NULL,
    STORE_STATUS_ID BIGINT NOT NULL,
    STORE_STATUS VARCHAR(250) NOT NULL,
    STORE_SIZE_SQM INT NOT NULL,
    OPENING_YEAR INT NOT NULL,
    HAS_GENIUS_BAR BOOLEAN NOT NULL,
    MANAGER_ID BIGINT NOT NULL,
    MANAGER_FIRST_NAME VARCHAR(250) NOT NULL,
    MANAGER_LAST_NAME VARCHAR(250) NOT NULL,
    ADDRESS_ID BIGINT NOT NULL,
    ADDRESS VARCHAR(350) NOT NULL,
    POSTAL_CODE VARCHAR(250) NOT NULL,
    DISTRICT_ID BIGINT NOT NULL,
    DISTRICT_NAME VARCHAR(250) NOT NULL,
    CITY_ID BIGINT NOT NULL,
    CITY_NAME VARCHAR(250) NOT NULL,
    STATE_ID BIGINT NOT NULL,
    STATE_NAME VARCHAR(250) NOT NULL,
    COUNTRY_ID BIGINT NOT NULL,
    COUNTRY_NAME VARCHAR(100) NOT NULL,
    REGION_ID BIGINT NOT NULL,
    REGION_NAME VARCHAR(250) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL,
    CONSTRAINT PK_DIM_STORES PRIMARY KEY (STORE_SURR_ID),
    CONSTRAINT UNQ_DIM_STORES_SRC UNIQUE (STORE_SRC_ID, SOURCE_SYSTEM)
);
--DIM_EMPLOYEES
CREATE TABLE IF NOT EXISTS BL_DM.DIM_EMPLOYEES (
    EMPLOYEE_SURR_ID BIGINT NOT NULL,
    EMPLOYEE_SRC_ID BIGINT NOT NULL,
    FIRST_NAME VARCHAR(250) NOT NULL,
    LAST_NAME VARCHAR(250) NOT NULL,
    POSITION_ID BIGINT NOT NULL,
    POSITION_NAME VARCHAR(250) NOT NULL,
    HIRE_DATE DATE NOT NULL,
    EMAIL VARCHAR(250) NOT NULL,
    PHONE VARCHAR(250) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL,
    CONSTRAINT PK_DIM_EMPLOYEES PRIMARY KEY (EMPLOYEE_SURR_ID),
    CONSTRAINT UNQ_DIM_EMP_SRC UNIQUE (EMPLOYEE_SRC_ID, SOURCE_SYSTEM)
);
--DIM_PROMOTIONS
CREATE TABLE IF NOT EXISTS BL_DM.DIM_PROMOTIONS (
    PROMOTION_SURR_ID BIGINT NOT NULL,
    PROMOTION_SRC_ID BIGINT NOT NULL,
    PROMOTION_NAME VARCHAR(250) NOT NULL,
    PROMOTION_TYPE_ID BIGINT NOT NULL,
    PROMOTION_TYPE VARCHAR(250) NOT NULL,
    IS_ACTIVE VARCHAR(10) NOT NULL,
    PROMO_START DATE NOT NULL,
    PROMO_END DATE NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL,
    CONSTRAINT PK_DIM_PROMOTIONS PRIMARY KEY (PROMOTION_SURR_ID),
    CONSTRAINT UNQ_DIM_PROMO_SRC UNIQUE (PROMOTION_SRC_ID, SOURCE_SYSTEM)
);
--DIM_PAYMENT_METHODS
CREATE TABLE IF NOT EXISTS BL_DM.DIM_PAYMENT_METHODS (
    PAYMENT_METHOD_SURR_ID BIGINT NOT NULL,
    PAYMENT_METHOD_SRC_ID BIGINT NOT NULL,
    PAYMENT_METHOD_NAME VARCHAR(250) NOT NULL,
    PAYMENT_METHOD_TYPE VARCHAR(250) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_ENTITY VARCHAR(50) NOT NULL,
    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL,
    CONSTRAINT PK_DIM_PAYMENT_METHODS PRIMARY KEY (PAYMENT_METHOD_SURR_ID),
    CONSTRAINT UNQ_DIM_PAY_SRC UNIQUE (PAYMENT_METHOD_SRC_ID, SOURCE_SYSTEM)
);
--DIM_DATES
CREATE TABLE IF NOT EXISTS BL_DM.DIM_DATES (
    DATE_SURR_ID BIGINT NOT NULL,           
    FULL_DATE DATE NOT NULL,          
    DAY_OF_WEEK VARCHAR(15) NOT NULL,   
    DAY_NUMBER INT NOT NULL,           
    MONTH_NUMBER INT NOT NULL,           
    MONTH_NAME VARCHAR(15) NOT NULL,   
    QUARTER INT NOT NULL,           
    YEAR INT NOT NULL,           
    INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    CONSTRAINT PK_DIM_DATES PRIMARY KEY (DATE_SURR_ID)
);
--FCT_SALES_DD
CREATE TABLE IF NOT EXISTS BL_DM.FCT_SALES_DD (
    SALE_SURR_ID BIGINT NOT NULL,
    SALE_SRC_ID BIGINT NOT NULL, 
    SALE_CHANNEL VARCHAR(250) NOT NULL,
    DATE_SURR_ID BIGINT NOT NULL REFERENCES BL_DM.DIM_DATES(DATE_SURR_ID), 
    PRODUCT_SURR_ID BIGINT NOT NULL REFERENCES BL_DM.DIM_PRODUCTS_SCD(PRODUCT_SURR_ID),
    CUSTOMER_SURR_ID BIGINT NOT NULL REFERENCES BL_DM.DIM_CUSTOMERS(CUSTOMER_SURR_ID),
    STORE_SURR_ID BIGINT NOT NULL REFERENCES BL_DM.DIM_STORES(STORE_SURR_ID),
    EMPLOYEE_SURR_ID BIGINT NOT NULL REFERENCES BL_DM.DIM_EMPLOYEES(EMPLOYEE_SURR_ID),
    PAYMENT_METHOD_SURR_ID BIGINT NOT NULL REFERENCES BL_DM.DIM_PAYMENT_METHODS(PAYMENT_METHOD_SURR_ID),
    PROMOTION_SURR_ID BIGINT NOT NULL REFERENCES BL_DM.DIM_PROMOTIONS(PROMOTION_SURR_ID),
    DISCOUNT_VALUE DECIMAL(10,2) NOT NULL,
    QUANTITY INT,
    UNIT_PRICE DECIMAL(18,2),
    UNIT_COST DECIMAL(18,2),
    TOTAL_REVENUE DECIMAL(18,2),
    GROSS_PROFIT DECIMAL(18,2),
    INSERT_DT TIMESTAMP NOT NULL,
    CONSTRAINT PK_FCT_SALES_DD PRIMARY KEY (SALE_SURR_ID, DATE_SURR_ID)
) PARTITION BY RANGE (DATE_SURR_ID);
COMMIT;



