
--Create table to sql test query
CREATE TABLE IF NOT EXISTS BL_CL.T_DATA_QUALITY_TESTS (
    test_id SERIAL PRIMARY KEY,
    test_group VARCHAR(50),
    test_description TEXT,
    test_query TEXT,             --should return 0 on success
    expected_result INT DEFAULT 0,
    is_critical BOOLEAN DEFAULT FALSE, 
    is_active BOOLEAN DEFAULT TRUE
);

--insert sql test queries
INSERT INTO BL_CL.T_DATA_QUALITY_TESTS (test_group, test_description, test_query) VALUES
--check Duplicates on BL_3NF
('Duplicates', 'Duplicates in CE_REGIONS', 'SELECT COUNT(*) FROM (SELECT REGION_ID FROM BL_3NF.CE_REGIONS GROUP BY REGION_ID HAVING COUNT(*) > 1) t'),
('Duplicates', 'Duplicates in CE_COUNTRIES', 'SELECT COUNT(*) FROM (SELECT COUNTRY_ID FROM BL_3NF.CE_COUNTRIES GROUP BY COUNTRY_ID HAVING COUNT(*) > 1) t'),
('Duplicates', 'Duplicates in CE_STATES', 'SELECT COUNT(*) FROM (SELECT STATE_ID FROM BL_3NF.CE_STATES GROUP BY STATE_ID HAVING COUNT(*) > 1) t'),
('Duplicates', 'Duplicates in CE_CITIES', 'SELECT COUNT(*) FROM (SELECT CITY_ID FROM BL_3NF.CE_CITIES GROUP BY CITY_ID HAVING COUNT(*) > 1) t'),
('Duplicates', 'Duplicates in CE_DISTRICTS', 'SELECT COUNT(*) FROM (SELECT DISTRICT_ID FROM BL_3NF.CE_DISTRICTS GROUP BY DISTRICT_ID HAVING COUNT(*) > 1) t'),
('Duplicates', 'Duplicates in CE_ADDRESSES', 'SELECT COUNT(*) FROM (SELECT ADDRESS_ID FROM BL_3NF.CE_ADDRESSES GROUP BY ADDRESS_ID HAVING COUNT(*) > 1) t'),
('Duplicates', 'Duplicates in CE_PRODUCTS_SCD', 'SELECT COUNT(*) FROM (SELECT PRODUCT_ID, START_DT FROM BL_3NF.CE_PRODUCTS_SCD GROUP BY PRODUCT_ID, START_DT HAVING COUNT(*) > 1) t'),
('Duplicates', 'Duplicates in CE_CATEGORIES', 'SELECT COUNT(*) FROM (SELECT CATEGORY_ID FROM BL_3NF.CE_CATEGORIES GROUP BY CATEGORY_ID HAVING COUNT(*) > 1) t'),
('Duplicates', 'Duplicates in CE_SUBCATEGORIES', 'SELECT COUNT(*) FROM (SELECT SUBCATEGORY_ID FROM BL_3NF.CE_SUBCATEGORIES GROUP BY SUBCATEGORY_ID HAVING COUNT(*) > 1) t'),
('Duplicates', 'Duplicates in CE_COLORS', 'SELECT COUNT(*) FROM (SELECT COLOR_ID FROM BL_3NF.CE_COLORS GROUP BY COLOR_ID HAVING COUNT(*) > 1) t'),
('Duplicates', 'Duplicates in CE_STORAGE_CAPACITIES', 'SELECT COUNT(*) FROM (SELECT STORAGE_CAPACITY_ID FROM BL_3NF.CE_STORAGE_CAPACITIES GROUP BY STORAGE_CAPACITY_ID HAVING COUNT(*) > 1) t'),
('Duplicates', 'Duplicates in CE_CUSTOMERS', 'SELECT COUNT(*) FROM (SELECT CUSTOMER_ID FROM BL_3NF.CE_CUSTOMERS GROUP BY CUSTOMER_ID HAVING COUNT(*) > 1) t'),
('Duplicates', 'Duplicates in CE_SEGMENTS', 'SELECT COUNT(*) FROM (SELECT SEGMENT_ID FROM BL_3NF.CE_SEGMENTS GROUP BY SEGMENT_ID HAVING COUNT(*) > 1) t'),
('Duplicates', 'Duplicates in CE_EMPLOYEES', 'SELECT COUNT(*) FROM (SELECT EMPLOYEE_ID FROM BL_3NF.CE_EMPLOYEES GROUP BY EMPLOYEE_ID HAVING COUNT(*) > 1) t'),
('Duplicates', 'Duplicates in CE_POSITIONS', 'SELECT COUNT(*) FROM (SELECT POSITION_ID FROM BL_3NF.CE_POSITIONS GROUP BY POSITION_ID HAVING COUNT(*) > 1) t'),
('Duplicates', 'Duplicates in CE_STORES', 'SELECT COUNT(*) FROM (SELECT STORE_ID FROM BL_3NF.CE_STORES GROUP BY STORE_ID HAVING COUNT(*) > 1) t'),
('Duplicates', 'Duplicates in CE_STORE_TYPES', 'SELECT COUNT(*) FROM (SELECT STORE_TYPE_ID FROM BL_3NF.CE_STORE_TYPES GROUP BY STORE_TYPE_ID HAVING COUNT(*) > 1) t'),
('Duplicates', 'Duplicates in CE_STORE_STATUSES', 'SELECT COUNT(*) FROM (SELECT STORE_STATUS_ID FROM BL_3NF.CE_STORE_STATUSES GROUP BY STORE_STATUS_ID HAVING COUNT(*) > 1) t'),
('Duplicates', 'Duplicates in CE_PROMOTIONS', 'SELECT COUNT(*) FROM (SELECT PROMOTION_ID FROM BL_3NF.CE_PROMOTIONS GROUP BY PROMOTION_ID HAVING COUNT(*) > 1) t'),
('Duplicates', 'Duplicates in CE_PROMOTION_TYPES', 'SELECT COUNT(*) FROM (SELECT PROMOTION_TYPE_ID FROM BL_3NF.CE_PROMOTION_TYPES GROUP BY PROMOTION_TYPE_ID HAVING COUNT(*) > 1) t'),
('Duplicates', 'Duplicates in CE_PAYMENT_METHODS', 'SELECT COUNT(*) FROM (SELECT PAYMENT_METHOD_ID FROM BL_3NF.CE_PAYMENT_METHODS GROUP BY PAYMENT_METHOD_ID HAVING COUNT(*) > 1) t'),
('Duplicates', 'Duplicates in CE_SALES', 'SELECT COUNT(*) FROM (SELECT SALE_ID FROM BL_3NF.CE_SALES GROUP BY SALE_ID HAVING COUNT(*) > 1) t'),
--check Duplicates on BL_DM
('Duplicates DM', 'Duplicates in DIM_PRODUCTS_SCD', 'SELECT COUNT(*) FROM (SELECT PRODUCT_SURR_ID FROM BL_DM.DIM_PRODUCTS_SCD GROUP BY PRODUCT_SURR_ID HAVING COUNT(*) > 1) t'),
('Duplicates DM', 'Duplicates in DIM_CUSTOMERS', 'SELECT COUNT(*) FROM (SELECT CUSTOMER_SURR_ID FROM BL_DM.DIM_CUSTOMERS GROUP BY CUSTOMER_SURR_ID HAVING COUNT(*) > 1) t'),
('Duplicates DM', 'Duplicates in FCT_SALES_DD', 'SELECT COUNT(*) FROM (SELECT SALE_SURR_ID, DATE_SURR_ID FROM BL_DM.FCT_SALES_DD GROUP BY SALE_SURR_ID, DATE_SURR_ID HAVING COUNT(*) > 1) t'),
('Duplicates DM', 'Duplicates in DIM_PAYMENT_METHODS', 'SELECT COUNT(*) FROM (SELECT PAYMENT_METHOD_SURR_ID FROM BL_DM.DIM_PAYMENT_METHODS GROUP BY PAYMENT_METHOD_SURR_ID HAVING COUNT(*) > 1) t'),
('Duplicates DM', 'Duplicates in DIM_PROMOTIONS', 'SELECT COUNT(*) FROM (SELECT PROMOTION_SURR_ID FROM BL_DM.DIM_PROMOTIONS GROUP BY PROMOTION_SURR_ID HAVING COUNT(*) > 1) t'),
('Duplicates DM', 'Duplicates in DIM_EMPLOYEES', 'SELECT COUNT(*) FROM (SELECT EMPLOYEE_SURR_ID FROM BL_DM.DIM_EMPLOYEES GROUP BY EMPLOYEE_SURR_ID HAVING COUNT(*) > 1) t'),
('Duplicates DM', 'Duplicates in DIM_STORES', 'SELECT COUNT(*) FROM (SELECT STORE_SURR_ID FROM BL_DM.DIM_STORES GROUP BY STORE_SURR_ID HAVING COUNT(*) > 1) t'),
--check all data presented
('Fullness', 'POS Sales: SA vs 3NF', 
 'SELECT ABS((SELECT COUNT(DISTINCT sale_id) FROM SA_APPLE_POS.SRC_APPLE_POS) - (SELECT COUNT(*) FROM BL_3NF.CE_SALES WHERE SALE_CHANNEL = ''POS''))'),
('Fullness', 'ONLINE Sales: SA vs 3NF', 
 'SELECT ABS((SELECT COUNT(DISTINCT order_code) FROM SA_APPLE_ONLINE.SRC_APPLE_ONLINE) - (SELECT COUNT(*) FROM BL_3NF.CE_SALES WHERE SALE_CHANNEL = ''ONLINE''))'),
--Compare 3NF and DM
('Fullness', 'Reconciliation: 3NF Sales vs DM Sales', 'SELECT ABS((SELECT COUNT(*) FROM BL_3NF.CE_SALES WHERE SALE_ID <> -1) - 
(SELECT COUNT(*) FROM BL_DM.FCT_SALES_DD WHERE SALE_SURR_ID <> -1))'); 
 
 
 --Create procedures to execute all tests
CREATE OR REPLACE PROCEDURE BL_CL.PRC_RUN_DATA_QUALITY_TESTS()
LANGUAGE plpgsql AS $$
DECLARE
    v_test RECORD;
    v_actual_result INT;
    v_status VARCHAR(20);
BEGIN
    FOR v_test IN (SELECT * FROM BL_CL.T_DATA_QUALITY_TESTS WHERE is_active = TRUE) 
    LOOP
        EXECUTE v_test.test_query INTO v_actual_result;
        IF v_actual_result = v_test.expected_result THEN
            v_status := 'PASSED';
        ELSE
            v_status := 'FAILED';
        END IF;
        CALL BL_CL.PRC_WRITE_LOG(
            'DQ_TEST_' || v_test.test_id, 
            v_actual_result, 
            v_status, 
            v_test.test_description);
        IF v_status = 'FAILED' AND v_test.is_critical THEN
             RAISE EXCEPTION 'Test % failed: %', v_test.test_id, v_test.test_description;
        END IF;
    END LOOP;
END; $$;

 
 
 
 
 
 
